// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfoyVBf7sK2K2NlfoBXd3s4wOqAyW3b8o',
    appId: '1:689228076617:web:cf629afb9e8e9495ea9198',
    messagingSenderId: '689228076617',
    projectId: 'gabutinc',
    authDomain: 'gabutinc.firebaseapp.com',
    storageBucket: 'gabutinc.firebasestorage.app',
    measurementId: 'G-L2X5SXE4BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDc1gZtQ_n1dvrKFhUnCt65S4sPz51NOw',
    appId: '1:689228076617:android:6f2d1f575284429fea9198',
    messagingSenderId: '689228076617',
    projectId: 'gabutinc',
    storageBucket: 'gabutinc.firebasestorage.app',
  );
}
